sudo: false
language: node_js
node_js: 10
addons:
  chrome: stable
before_install:
- export TRAVIS_COMMIT_MSG="[deploy] $(git log --format='%h - %B' --no-merges -n 1)"
- export TRAVIS_COMMIT_USER="$(git log --no-merges -n 1 --format=%an)"
- export TRAVIS_COMMIT_EMAIL="$(git log --no-merges -n 1 --format=%ae)"
after_success:
- sh build/deploy-ci.sh
- cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls
  global:
  secure: "gAz3gW+gWjlBoYATj75qh2iSRoytbTalFnkqhYJY6WxMInn1zmwUd8d+n6Ov1efOxk0FWl7KCG3pqDVF9Iwdb2umMTihiKl2LMp9VSeijBuF8x6sluJzk6AsEYokiJ6eAA4htJjjWn9Cm/p2zc+eEVvpnZYjLJ157cBLQ79nE
Bgw/JJ0Niq+v6Qs1zZWhBjhuajpPVamPIMKGvvSaRyuwsuY606depY126T2UpW2xydD/I+FSMTXF729kZeUB3gOCXF+jBD7waqrW0ou75Ke5efHmzAs1DRgFOxP12K6fhYt+emljOrL+8j8IdQPgRPN8D+GLEb8uDGdAVOyyzQIxMR1TPBvA
hVMG+eUL8K31zEB59cAmCYTTaV1Na5X9oTEoHTyJvHJppBtcx3J1lkD+uu4TMpVS4gJMWJr0oyyyohHmcF5cXL2wjNeJXxFqRYSjxMMr/+n44pBv1C6tnwlATE0S49kJxhZqF0tKcVW3Zx5vfK5qvNJNd6rXlZYzxH/JfKLncnmUnjb+VJcJ
MKAH6GuOYuVNYu17DEfrklpCsbErzMavDh0i6bu8Pk14TPnG4sTt7c87GOUDPvAfwTmCypAaCnwZmO56zZ2eaHZFsJlNrv0Iw7KFlBi8oV2nZRWZLAaDmFWL/96CjEYYQRYiGsBvm7nFW4lZq04NWfLbDk="
